name: 12_FrontEnd_CICD

on:  
  push:     
    branches: [ master, fb-** ]
    paths:
      - '02_FrontEnd/**'
      - '.github/workflows/**' 
  
  workflow_run:
    workflows: ["02_Initial_Setup_All_Infra"]
    branches: [master]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest   

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master   

    - name: 'Load env variable from file using pwsh'
      shell: pwsh
      run: 03_IaC/00_AzureCLI/10_LoadEnvVariables.ps1    
    
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
        
    - name: 'Build Front End'
      working-directory: 02_FrontEnd
      run: |
        az extension add --name application-insights
        $appInsightsKey = az monitor app-insights component show --app ${{env.projectPrefix}}teamsTabAI -g ${{env.projectPrefix}}_rg --query 'instrumentationKey'
        $staticSiteUrl = az storage account show -n ${{env.projectPrefix}}site -g ${{env.projectPrefix}}_rg --query "primaryEndpoints.web" --output tsv
        $staticSiteUrl = $staticSiteUrl.replace("https://","").replace("/","")
        Write-Output "PACKAGE_NAME=cognitivebot" | Out-File -FilePath .env -Encoding utf8 -Append
        Write-Output "APPLICATION_ID=e6b3dba0-af0b-11eb-bed7-4980d524c0d2" | Out-File -FilePath .env -Encoding utf8 -Append
        Write-Output "HOSTNAME=$staticSiteUrl" | Out-File -FilePath .env -Encoding utf8 -Append
        Write-Output "REACT_APP_BACKEND_DOMAIN=${{env.projectPrefix}}middleware.azurewebsites.net" | Out-File -FilePath .env -Encoding utf8 -Append
        Write-Output "REACT_APP_BACKEND_API=https://${{env.projectPrefix}}middleware.azurewebsites.net/" | Out-File -FilePath .env -Encoding utf8 -Append        
        Write-Output "APPINSIGHTS_INSTRUMENTATIONKEY=$appInsightsKey" | Out-File -FilePath .env -Encoding utf8 -Append
        Get-Content .env
        npm install
        gulp build
        gulp manifest  
    
        
    - name: 'Push to Azure Storage Static Site'
      working-directory: 02_FrontEnd
      shell: pwsh # $projectPrefix +"site"
      run: |
        az storage blob delete-batch -s '$web' --account-name ${{env.projectPrefix}}site
        pushd ./dist/web
        az storage blob upload-batch --account-name ${{env.projectPrefix}}site --source . --destination '$web'
        pushd ../../package
        az storage blob upload-batch --account-name ${{env.projectPrefix}}site --source . --destination '$web'